seed_data = [
    {
        'name': 'iPhone 13',
        'description': 'The latest iPhone model with advanced features.',
        'os': 'ios',
        'price': 999.99,
        'quantity': 50,
    },
    {
        'name': 'Samsung Galaxy S21',
        'description': 'A flagship Android smartphone with a stunning display.',
        'os': 'android',
        'price': 899.99,
        'quantity': 30,
    },
    {
        'name': 'Dell XPS 13',
        'description': 'A powerful and compact laptop for productivity.',
        'os': 'windows',
        'price': 1299.99,
        'quantity': 20,
    },
    {
        'name': 'MacBook Pro',
        'description': 'Apple\'s professional laptop with exceptional performance.',
        'os': 'ios',
        'price': 1799.99,
        'quantity': 15,
    },
    {
        'name': 'Google Pixel 6',
        'description': 'A high-end Android smartphone with a great camera.',
        'os': 'android',
        'price': 799.99,
        'quantity': 40,
    },
    {
        'name': 'Lenovo ThinkPad X1 Carbon',
        'description': 'A premium business laptop known for its durability.',
        'os': 'windows',
        'price': 1499.99,
        'quantity': 25,
    },
    {
        'name': 'iPad Air',
        'description': 'A lightweight tablet with a powerful A14 Bionic chip.',
        'os': 'ios',
        'price': 599.99,
        'quantity': 35,
    },
    {
        'name': 'OnePlus 9 Pro',
        'description': 'A flagship Android smartphone with a smooth 120Hz display.',
        'os': 'android',
        'price': 899.99,
        'quantity': 30,
    },
    {
        'name': 'Microsoft Surface Laptop 4',
        'description': 'A sleek and powerful laptop with a touchscreen display.',
        'os': 'windows',
        'price': 1299.99,
        'quantity': 20,
    },
    {
        'name': 'Sony Xperia 5 III',
        'description': 'A compact Android smartphone with advanced camera features.',
        'os': 'android',
        'price': 999.99,
        'quantity': 25,
    },

    {
        'name': 'HP Spectre x360',
        'description': 'A versatile 2-in-1 laptop with a stunning design.',
        'os': 'windows',
        'price': 1299.99,
        'quantity': 15,
    },
    {
        'name': 'Xiaomi Mi 11',
        'description': 'A flagship Android smartphone with a powerful Snapdragon processor.',
        'os': 'android',
        'price': 699.99,
        'quantity': 35,
    },
    {
        'name': 'Asus ZenBook 14',
        'description': 'An ultraportable laptop with a high-resolution display.',
        'os': 'windows',
        'price': 999.99,
        'quantity': 20,
    },
    {
        'name': 'LG V60 ThinQ',
        'description': 'A dual-screen Android smartphone with a focus on multimedia.',
        'os': 'android',
        'price': 699.99,
        'quantity': 30,
    },
    {
        'name': 'Surface Pro 8',
        'description': 'Microsoft\'s latest 2-in-1 tablet with a high-resolution display.',
        'os': 'windows',
        'price': 1099.99,
        'quantity': 25,
    },
    {
        'name': 'Motorola Edge+',
        'description': 'A 5G Android smartphone with a large OLED display.',
        'os': 'android',
        'price': 899.99,
        'quantity': 20,
    },
    {
        'name': 'Razer Blade 15',
        'description': 'A gaming laptop with a high-refresh-rate display and powerful GPU.',
        'os': 'windows',
        'price': 1999.99,
        'quantity': 10,
    },
    {
        'name': 'iPhone SE',
        'description': 'A compact and affordable iPhone with the latest processor.',
        'os': 'ios',
        'price': 399.99,
        'quantity': 40,
    },
    {
        'name': 'Samsung Galaxy Tab S7',
        'description': 'A premium Android tablet with a high-refresh-rate display.',
        'os': 'android',
        'price': 649.99,
        'quantity': 15,
    },
    {
        'name': 'Acer Chromebook Spin 713',
        'description': 'A Chromebook with a 2K display and 10th Gen Intel Core processor.',
        'os': 'android',
        'price': 629.99,
        'quantity': 20,
    },

]
