# Generated by Django 5.2.7 on 2025-11-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailsentflag',
            field=models.BooleanField(default=False),
        ),
    ]
